spring.application.name=monitor
server.port=8080

# MQTT (Mosquitto) configuration
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=monitor-client
mqtt.username=alex
mqtt.password=123
mqtt.default-topic=monitor/#
mqtt.qos=1
mqtt.keep-alive-interval=60
mqtt.connection-timeout=30

